SELECT 
UPPER('us') as upperCase,
LOWER('US') as lowerCase,
INITCAP('united states') as InitCap,
SUBSTR('United States', 8) as substr,
SUBSTR('United States', 8, 5) as substr2,
CONCAT('U', 'S') as concat1,
'U'||'S'||'A' as concat2,
INSTR('Inited States', 'States') as Contains_position,
LPAD('USA', 7, '*') leftPad,
RPAD('USA', 7, '*') rightPad,
LPAD('USA', 7) leftPad_blank,
LENGTH(LPAD('USA', 7)) afterDefaultPadding,
RPAD('USA', 7) rightPad_blank,
LENGTH(RPAD('USA',7)) afterDefaultPadding2,
LENGTH('---US---' ) length,
LTRIM('---US---', '-') ltrim,
LTRIM('     US     ') ltrim_default,
LENGTH(LTRIM('     US     ')) as spaceTrimmed,
RTRIM('---US---', '-') rtrim,
RTRIM('     US     ') rtrim_default,
TRIM('-' FROM '---US---') trimmed,
TRIM(BOTH '-' FROM '---US---') both_trimmed,
TRIM(LEADING '-' FROM '---US---') L_Trimmed,
TRIM(TRAILING '-' FROM '---US---') T_Trimmed,
TRIM('   United States  ') trimSpace,
SOUNDEX('United States') sounds
FROM DUAL;

'''
    "uppercase": "US",
    "lowercase": "us",
    "initcap": "United States",
    "substr": "States",
    "substr2": "State",
    "concat1": "US",
    "concat2": "USA",
    "contains_position": 8,
    "leftpad": "****USA",
    "rightpad": "USA****",
    "leftpad_blank": "    USA",
    "afterdefaultpadding": 7,
    "rightpad_blank": "USA    ",
    "afterdefaultpadding2": 7,
    "length": 8,
    "ltrim": "US---",
    "ltrim_default": "US     ",
    "spacetrimmed": 7,
    "rtrim": "---US",
    "rtrim_default": "     US",
    "trimmed": "US",
    "both_trimmed": "US",
    "l_trimmed": "US---",
    "t_trimmed": "---US",
    "trimspace": "United States",
    "sounds": "U533"
'''
